name: ci

env:
  CONFIG_REPO_NAME: fibs-app-config

on:
  push:
    branches:
      - 'main'

jobs:
  build-info-prompt:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest
      -
        name: Run tests with pytest
        run: pytest tests/
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/arm64
          tags: xianfengyuan/fibs-app:${{ github.sha }}
  promote-to-target-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          echo "promoting into target environment!"
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          echo "cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          echo "checkout target branch"
          git checkout main
          echo "updating image tag in values file"
          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," helm/fibs-app/values.yaml
          git add . && git commit -m "update image tag"
          git push
